---
hooks:
    # "before:init":           npm i -D && npm shrinkwrap
    # "before:bump":           bin/bump.sh ${version}
    # "after:bump":            npm run clean && npm run build && nova extension validate Stylelint.novaextension
    # "before:github:release": bin/pack.sh ${version}
    # "after:release":         nova extension publish Stylelint.novaextension --no-confirm
    "before:init":
        - npm i -D
        - npm shrinkwrap
    "before:bump":
        - bin/bump.sh ${version}
    "after:bump":
        - npm run clean
        - npm run build
        - bin/pack.sh ${version}
        - nova extension validate Stylelint.novaextension
    "after:release":
        - nova extension publish Stylelint.novaextension --no-confirm

git:
    requireCleanWorkingDir: false
    requireBranch:          master
    requireCommits:         true
    addUntrackedFiles:      true
    commit:                 true
    commitMessage:          Release v${version}
    releaseName:            v${version}
    tagAnnotation:          Version ${version}
    tagArgs:                -s

github:
    release:      true
    releaseName:  v${version}
    releaseNotes: bin/notes.sh ${latestVersion} ${version}
    assets:       bin/Stylelint.novaextension-v${version}.tar.xz
    tokenRef:     RELEASE_IT

npm:
    publish: false
