---
hooks:
    "before:init":        npm run clean && npm run build
    "before:bump":        bin/bump.sh ${version}
    "after:bump":         nova extension validate Stylelint.novaextension
    "before:git:release": bin/pack.sh ${version}
    "after:git:release":  nova extension publish Stylelint.novaextension --no-confirm

git:
    requireCleanWorkingDir: false
      #requireBranch:          master
    requireCommits:         true
    addUntrackedFiles:      true
    commit:                 true
    commitMessage:          Release v${version}
    releaseName:            v${version}
    tagAnnotation:          Version ${version}
    tagArgs:                -s

github:
    release:      true
    releaseNotes: bin/notes.sh ${latestVersion} ${version}
    assets:       bin/Stylelint-v${version}.novaextension.tar.xz
    tokenRef:     RELEASE_IT

npm:
    publish: false
